# Site settings
title: LintBleed developer blog
email: veit.scharf@gmail.com
description: "Blog about the development of a static code analyzer capable of detecting the heartbleed bug in OpenSSL prior to version 1.0.1g."
baseurl: ""
url: "http://vscharf.github.io"
twitter_username: veitscharf
github_username: vscharf

# Build settings
markdown: kramdown
permalink: pretty
